In [1]:
import numpy as np
b = np.array([0]*10)
print(b)

[0 0 0 0 0 0 0 0 0 0]


In [2]:
c = np.array([1]*10)
print(c)

[1 1 1 1 1 1 1 1 1 1]


In [3]:
d = np.array([5]*10)
print(d)

[5 5 5 5 5 5 5 5 5 5]


In [4]:
e = np.array([i for i in range(10,50)])
print(e)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [5]:
f = ([x for x in range(10, 50, 2)])
print(f)

[10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48]


In [6]:
g = np.arange(9).reshape(3,3)
print(g)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
h = np.eye(3)
print(h)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
import random
print(random.uniform(0,1))

0.08743832630151638


In [10]:
j = np.random.normal(0,1,25)
print(j)

[-0.21576558 -1.17599283  1.38058405 -0.54006159  0.51978039  0.45745317
  2.22418784 -1.36190309 -1.27626656  0.01147814  1.07580855  0.14312628
 -0.2737351   0.89276699 -0.21769227  0.80505162  0.82278636  0.63563452
 -0.38312919  1.61658351  0.65553159 -0.4551918   1.8888889   1.23912415
 -1.36365487]


In [11]:
m=np.arange(0.01, 1.01, 0.01)
k = m.reshape((10, 10))
print(k)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [12]:
mat = np.arange(1,26).reshape(5,5)
print(mat)
print(mat[2:5, 1:5])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [13]:
m = mat[3, 4]
print(m)

20


In [14]:
n = mat[:3, 1]
n2 = n.reshape(3,1)
print(n2)

[[ 2]
 [ 7]
 [12]]


In [15]:
o = mat[4]
print(o)

[21 22 23 24 25]


In [16]:
p = mat[3:]
print(p)

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [17]:
sum_q = np.sum(mat)
print(sum_q)

325


In [18]:
r = np.std(mat)
print(r)

7.211102550927978


In [19]:
s = np.sum(mat, axis = 0)
print(s)

[55 60 65 70 75]
